apiVersion: v1
kind: Service
metadata:
  name: {{ include "experiment-chart.fullname" . }}
  labels:
    {{- include "experiment-chart.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: swim
      protocol: UDP
      name: swim
  selector:
    {{- include "experiment-chart.selectorLabels" . | nindent 4 }}
